# SPDX-License-Identifier: AGPL-3.0-only

# ████████████████████████████████████████████████
# █─▄▄▄─█▄─██─▄█▄─▄█▄─▀─▄█▄─▄─▀█▄─█─▄█─▄─▄─█▄─▄▄─█
# █─██▀─██─██─███─███▀─▀███─▄─▀██▄─▄████─████─▄█▀█
# ▀───▄▄▀▀▄▄▄▄▀▀▄▄▄▀▄▄█▄▄▀▄▄▄▄▀▀▀▄▄▄▀▀▀▄▄▄▀▀▄▄▄▄▄▀
# https://github.com/QuixByte/qb/blob/main/LICENSE
# 
# (c) Copyright 2023 The QuixByte Authors

version: "3.8"

services:
  qb-db:
    image: postgres
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: quixbyte
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
  qb-cache:
    image: redis
  qb-proxy:
    build:
      context: .
      dockerfile: ./qb-proxy/dev.Dockerfile
    links:
      - "qb-backend"
      - "qb-frontend"
    ports:
      - "8080:8080"
  qb-frontend:
    build:
      context: .
      dockerfile: ./qb-frontend/dev.Dockerfile
    volumes:
      - ./:/app
  qb-backend:
    build:
      context: .
      dockerfile: ./qb-backend/dev.Dockerfile
      args:
        FEATURES: postgres
    environment:
      REDIS_URL: redis://qb-cache
      DATABASE_URL: postgres://qb:qb@qb-db/qb
    links:
      - "qb-db"
      - "qb-cache"
    volumes:
      - ./:/app

volumes:
  db_data:
